# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewYorkTimeTEST' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewYorkTimeTEST
  
  pod 'FSPagerView'
  pod 'Kingfisher'

  target 'NewYorkTimeTESTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewYorkTimeTESTUITests' do
    # Pods for testing
  end

end
